New-Item -ItemType File -Path "src/app/core/guards/auth.guard.ts" -Force
New-Item -ItemType File -Path "src/app/core/guards/public.guard.ts" -Force
New-Item -ItemType File -Path "src/app/core/interceptors/auth.interceptor.ts" -Force
New-Item -ItemType File -Path "src/app/core/interceptors/error.interceptor.ts" -Force
New-Item -ItemType File -Path "src/app/core/interceptors/loader.interceptor.ts" -Force
New-Item -ItemType File -Path "src/app/core/models/user.model.ts" -Force
New-Item -ItemType File -Path "src/app/core/models/portfolio.model.ts" -Force
New-Item -ItemType File -Path "src/app/core/models/api-response.model.ts" -Force
New-Item -ItemType File -Path "src/app/core/services/auth-state.service.ts" -Force
New-Item -ItemType File -Path "src/app/core/services/token.service.ts" -Force
New-Item -ItemType File -Path "src/app/core/services/api.service.ts" -Force
New-Item -ItemType File -Path "src/app/core/utils/storage.utils.ts" -Force
New-Item -ItemType File -Path "src/app/core/utils/validation.utils.ts" -Force
New-Item -ItemType File -Path "src/app/core/core.providers.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/login-form/login-form.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/login-form/login-form.component.html" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/login-form/login-form.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/register-form/register-form.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/register-form/register-form.component.html" -Force
New-Item -ItemType File -Path "src/app/features/auth/components/register-form/register-form.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/login-page/login-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/login-page/login-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/login-page/login-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/register-page/register-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/register-page/register-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/auth/pages/register-page/register-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/auth/services/auth.service.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/auth.routes.ts" -Force
New-Item -ItemType File -Path "src/app/features/auth/auth.providers.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-stats/dashboard-stats.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-stats/dashboard-stats.component.html" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-stats/dashboard-stats.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-activity/dashboard-activity.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-activity/dashboard-activity.component.html" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/dashboard-activity/dashboard-activity.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/portfolio-list/portfolio-list.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/portfolio-list/portfolio-list.component.html" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/components/portfolio-list/portfolio-list.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/pages/dashboard-page/dashboard-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/pages/dashboard-page/dashboard-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/pages/dashboard-page/dashboard-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/services/dashboard.service.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/dashboard.routes.ts" -Force
New-Item -ItemType File -Path "src/app/features/dashboard/dashboard.providers.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-editor/portfolio-editor.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-editor/portfolio-editor.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-editor/portfolio-editor.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-section/portfolio-section.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-section/portfolio-section.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-section/portfolio-section.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-preview/portfolio-preview.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-preview/portfolio-preview.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/components/portfolio-preview/portfolio-preview.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-create-page/portfolio-create-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-create-page/portfolio-create-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-create-page/portfolio-create-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-edit-page/portfolio-edit-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-edit-page/portfolio-edit-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-edit-page/portfolio-edit-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-view-page/portfolio-view-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-view-page/portfolio-view-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/pages/portfolio-view-page/portfolio-view-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/services/portfolio.service.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/portfolio.routes.ts" -Force
New-Item -ItemType File -Path "src/app/features/portfolio/portfolio.providers.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/profile-editor/profile-editor.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/profile-editor/profile-editor.component.html" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/profile-editor/profile-editor.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/avatar-uploader/avatar-uploader.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/avatar-uploader/avatar-uploader.component.html" -Force
New-Item -ItemType File -Path "src/app/features/profile/components/avatar-uploader/avatar-uploader.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/profile/pages/profile-page/profile-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/pages/profile-page/profile-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/profile/pages/profile-page/profile-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/profile/services/profile.service.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/profile.routes.ts" -Force
New-Item -ItemType File -Path "src/app/features/profile/profile.providers.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-portfolio/public-portfolio.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-portfolio/public-portfolio.component.html" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-portfolio/public-portfolio.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-contact/public-contact.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-contact/public-contact.component.html" -Force
New-Item -ItemType File -Path "src/app/features/public/components/public-contact/public-contact.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/public-view-page/public-view-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/public-view-page/public-view-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/public-view-page/public-view-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/not-found-page/not-found-page.component.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/not-found-page/not-found-page.component.html" -Force
New-Item -ItemType File -Path "src/app/features/public/pages/not-found-page/not-found-page.component.scss" -Force
New-Item -ItemType File -Path "src/app/features/public/services/public.service.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/public.routes.ts" -Force
New-Item -ItemType File -Path "src/app/features/public/public.providers.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/button/button.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/button/button.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/button/button.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/card/card.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/card/card.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/card/card.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/form-field/form-field.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/form-field/form-field.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/form-field/form-field.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/toast/toast.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/toast/toast.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/toast/toast.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/loader/loader.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/loader/loader.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/loader/loader.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/modal/modal.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/modal/modal.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/ui/modal/modal.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/header/header.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/header/header.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/header/header.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/footer/footer.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/footer/footer.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/footer/footer.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/sidebar/sidebar.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/sidebar/sidebar.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/sidebar/sidebar.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/main-layout/main-layout.component.ts" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/main-layout/main-layout.component.html" -Force
New-Item -ItemType File -Path "src/app/shared/components/layout/main-layout/main-layout.component.scss" -Force
New-Item -ItemType File -Path "src/app/shared/directives/click-outside.directive.ts" -Force
New-Item -ItemType File -Path "src/app/shared/directives/lazy-load.directive.ts" -Force
New-Item -ItemType File -Path "src/app/shared/directives/debounce-click.directive.ts" -Force
New-Item -ItemType File -Path "src/app/shared/pipes/safe-html.pipe.ts" -Force
New-Item -ItemType File -Path "src/app/shared/pipes/time-ago.pipe.ts" -Force
New-Item -ItemType File -Path "src/app/shared/pipes/truncate.pipe.ts" -Force
New-Item -ItemType File -Path "src/app/shared/services/toast.service.ts" -Force
New-Item -ItemType File -Path "src/app/shared/services/loader.service.ts" -Force
New-Item -ItemType File -Path "src/app/shared/services/breakpoint.service.ts" -Force
New-Item -ItemType File -Path "src/app/shared/shared.providers.ts" -Force